#!/usr/bin/env node
/**
 * src/version.ts を自動生成する。
 *
 * - BUILD_VERSION: git short hash (+dirty なら "-dirty" 付与)
 * - BUILD_TIME:    UTC ISO 文字列
 *
 * build 前に動かすことで、deploy 済 bundle と repo の commit を一致確認できる。
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const target = resolve(projectRoot, 'src/version.ts');

function sh(cmd) {
  return execSync(cmd, { cwd: projectRoot, encoding: 'utf8' }).trim();
}

let hash = 'unknown';
let dirty = false;
try {
  hash = sh('git rev-parse --short HEAD');
  const status = sh('git status --porcelain');
  dirty = status.length > 0;
} catch {
  /* git 無しでもビルド継続 */
}

const version = dirty ? `${hash}-dirty` : hash;
const time = new Date().toISOString();

const body = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.
export const BUILD_VERSION = ${JSON.stringify(version)};
export const BUILD_TIME = ${JSON.stringify(time)};
`;
writeFileSync(target, body);
console.log(`[gen-version] ${version} @ ${time}`);
